plugins { id 'java' }
group = rootProject.group
version = rootProject.version
repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
}
dependencies {
    implementation project(':network')
    compileOnly 'com.velocitypowered:velocity-api:4.1.2-20260913.104530-4'
    annotationProcessor 'com.velocitypowered:velocity-api:4.1.2-20260913.104530-4'
    testImplementation platform('org.junit:junit-bom:5.13.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
test { useJUnitPlatform() }
tasks.withType(JavaCompile).configureEach { options.release = 25 }
jar {
    dependsOn ':network:jar'
    archiveBaseName = 'smash-proxy'
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from { configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) } }
    exclude 'META-INF/*.SF', 'META-INF/*.RSA', 'META-INF/*.DSA', 'module-info.class'
}
